### ISSUE TITLE
Enhancement in Attachment preview

### ISSUE THREAD

**Issue by saketkumar95** [kayako/Kayako-Android-SDK#15]
I had some ideas to have some options in Attachment Preview Layout.

- [ ]  Download Image option

- [ ] Zoomable Images

@metalwihen I did the zoomable images part. Just thought to ask you before sending the PR. Let me know what you think about the idea.

**Comment by metalwihen** [comment]
We don't need a share image option. But download image and zoomable image feature sounds really good. Send a PR.

**Comment by saketkumar95** [comment]
For Zoomable Images , I thought to use https://github.com/chrisbanes/PhotoView this library but there are many methods which will don't really need in the app currently. I used this library and apk size was increased by 20%. It's not good idea to have this just for one feature. 
I thought to create just a new zoomable imageView. Is it fine?

**Comment by metalwihen** [comment]
Yeah, I agree with you. Because this is an SDK, we're trying to reduce the size as much as possible. I'd rather not use a heavy library for the feature of zooming into images.
