### ISSUE TITLE
Add support for push notification

### ISSUE THREAD

**Issue by anjar10** [kayako/Kayako-Android-SDK#19]
Sometime user close the app before we can reply it.
I think push notification is the best method to notify user when we have reply the message.

**Comment by metalwihen** [comment]
Hey anjar10

Right now, we've done it in such a way that if the user leaves the Messenger (or app), he will receive an email. That way, we can ensure that the user will always be notified, whether he's online on the Messenger or not.

But push notifications are a good idea and it is something we're considering in the future. Thank you for the feedback.
